### PR TITLE
Misc build fixes

### PR DESCRIPTION
**Pull request by raffenet**

### CODE REVIEW

**Comment by raffenet** [comment]
@masamichitakagi a few fixes I needed to build on our systems.

**Review by masamichitakagi — APPROVED** [review]
LGTM.

**Review by masamichitakagi — APPROVED** [review]
LGTM.

**Review by masamichitakagi — APPROVED** [review]
Thanks!

**Review by masamichitakagi — APPROVED** [review]
Thanks!

**Comment by masamichitakagi** [comment]
All LGTM. Thanks!

**Pull request merged**
